-- Requete 1

SELECT SPORTIF.NOM, SPORTIF.PRENOM, SPORTIF.PAYS_ORIGINE, SPORT.NOM
FROM SPORTIF, SPORT, PRATIQUE
WHERE PRATIQUE.ID_SPORT = SPORT.ID_SPORT
AND SPORTIF.ID_SPORTIF = PRATIQUE.ID_SPORTIF
AND SPORT.NOM = 'rugby'
AND SPORTIF.PAYS_ORIGINE = 'angleterre'
ORDER BY SPORTIF.NOM, SPORTIF.PRENOM

-- Requete 2

SELECT c.ID_COMPETITION, c.NOM, c.ADRESSE, c.VILLE, c.CP, c.PAYS, c.DATE_DEBUT, c.DATE_FIN, count(ID_SPORTIF) 'nombre de participant' 
FROM Competition c, PARTICIPE
WHERE  c.ID_COMPETITION = PARTICIPE.ID_COMPETITION
GROUP BY c.ID_COMPETITION, c.NOM, c.ADRESSE, c.VILLE, c.CP, c.PAYS, c.DATE_DEBUT, c.DATE_FIN
Having count(ID_SPORTIF)> 1000 

-- Requete 3

UPDATE COMPETITION
SET DATE_DEBUT = '05/07/2022'
WHERE NOM = 'Meeting d''Athlétisme' AND VILLE = 'Zurich' AND PAYS = 'Suisse';

-- Requete 4

DELETE FROM COMPETITION 
WHERE DATE_FIN < '01/01/1990';
